#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/dm3q

PRODUCT_COPY_FILES += \
    vendor/samsung/dm3q/proprietary/odm/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b20 \
    vendor/samsung/dm3q/proprietary/odm/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mbn \
    vendor/samsung/dm3q/proprietary/odm/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mdt \
    vendor/samsung/dm3q/proprietary/odm/firmware/a740_zap.b02:$(TARGET_COPY_OUT_ODM)/firmware/a740_zap.b02 \
    vendor/samsung/dm3q/proprietary/odm/firmware/a740_zap.mbn:$(TARGET_COPY_OUT_ODM)/firmware/a740_zap.mbn \
    vendor/samsung/dm3q/proprietary/odm/firmware/a740_zap.mdt:$(TARGET_COPY_OUT_ODM)/firmware/a740_zap.mdt \
    vendor/samsung/dm3q/proprietary/odm/firmware/evass.b19:$(TARGET_COPY_OUT_ODM)/firmware/evass.b19 \
    vendor/samsung/dm3q/proprietary/odm/firmware/evass.mbn:$(TARGET_COPY_OUT_ODM)/firmware/evass.mbn \
    vendor/samsung/dm3q/proprietary/odm/firmware/evass.mdt:$(TARGET_COPY_OUT_ODM)/firmware/evass.mdt \
    vendor/samsung/dm3q/proprietary/odm/firmware/vpu30_4v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu30_4v.mbn \
    vendor/samsung/dm3q/proprietary/vendor/etc/audconf/OPEN/acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/acdb_cal.acdb \
    vendor/samsung/dm3q/proprietary/vendor/etc/audconf/OPEN/workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFileXml.qwsp \
    vendor/samsung/dm3q/proprietary/vendor/etc/audio/sku_kalama/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_kalama/mixer_paths.xml \
    vendor/samsung/dm3q/proprietary/vendor/etc/display/qdcm_calib_data_DM3_S6E3HAE_AMB681AZ01.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_DM3_S6E3HAE_AMB681AZ01.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/dm3q/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-qti.rc \
    vendor/samsung/dm3q/proprietary/vendor/etc/init/init.vendor.onebinary.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.onebinary.rc \
    vendor/samsung/dm3q/proprietary/vendor/etc/init/init.vendor.rilcommon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.rilcommon.rc \
    vendor/samsung/dm3q/proprietary/vendor/etc/init/vendor.samsung.rilchip.qcom.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rilchip.qcom.rc \
    vendor/samsung/dm3q/proprietary/vendor/etc/init/vendor.samsung.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.rild.rc \
    vendor/samsung/dm3q/proprietary/vendor/etc/nfc/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/libnfc-nxp_RF.conf \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_ak991x_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_ak991x_1.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_ak991x_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_ak991x_2.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_ak991x_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_ak991x_3.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_ak991x_8.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_ak991x_8.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_irq.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_lps22hh_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_lps22hh_0.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_lsm6dso_0_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_lsm6dso_0_0.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_lsm6dso_0_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_lsm6dso_0_1.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_lsm6dso_0_8.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_lsm6dso_0_8.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_stk3a9x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_stk3a9x_0.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/kailua_tmd4913_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_tmd4913_2.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0.json \
    vendor/samsung/dm3q/proprietary/vendor/etc/situation_audio_policy_volumes_sec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/situation_audio_policy_volumes_sec.xml \
    vendor/samsung/dm3q/proprietary/vendor/firmware/00_generic_xtalk_shape.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/00_generic_xtalk_shape.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b00 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b01 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b02 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b03 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b04 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b05 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b06 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b07 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b08 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b09 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b10 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b11 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b12 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b13 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b14 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b15 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b16 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b17 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b18 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b19 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/samsung/dm3q/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/samsung/dm3q/proprietary/vendor/firmware/DM3_S6E3HAE_AMB681AZ01.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/DM3_S6E3HAE_AMB681AZ01.dat \
    vendor/samsung/dm3q/proprietary/vendor/firmware/Data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/Data.msc \
    vendor/samsung/dm3q/proprietary/vendor/firmware/SoundBoosterParam.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/SoundBoosterParam.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/a740_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_sqe.fw \
    vendor/samsung/dm3q/proprietary/vendor/firmware/a740_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.b00 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/a740_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.b01 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/a740_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.b02 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/a740_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.elf \
    vendor/samsung/dm3q/proprietary/vendor/firmware/a740_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/a740_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.mdt \
    vendor/samsung/dm3q/proprietary/vendor/firmware/bt_nvm_loading.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_nvm_loading.xml \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs35l43-bot-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-bot-dsp1-spk-prot.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs35l43-bot-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-bot-dsp1-spk-prot.wmfw \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs35l43-rcv-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-rcv-dsp1-spk-prot.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs35l43-rcv-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l43-rcv-dsp1-spk-prot.wmfw \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-a2h.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-a2h.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-calib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-calib.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-calib.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-calib.wmfw \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-dvl.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-dvl.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-svc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-svc1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc1.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-svc2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc2.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-svc3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-svc3.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-wt1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-wt1.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-wt2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-wt2.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26-wt3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26-wt3.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/cs40l26.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l26.wmfw \
    vendor/samsung/dm3q/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b00 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/samsung/dm3q/proprietary/vendor/firmware/gmu_gen70200.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70200.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/hmtbtfw20.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtbtfw20.tlv \
    vendor/samsung/dm3q/proprietary/vendor/firmware/hmtnv20.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtnv20.b21 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/hmtnv20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hmtnv20.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/kiwi/amss20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/amss20.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/kiwi/bdwlan.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/bdwlan.elf \
    vendor/samsung/dm3q/proprietary/vendor/firmware/kiwi/bdwlan.elf1:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/bdwlan.elf1 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/kiwi/bdwlan.elf10:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/bdwlan.elf10 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/kiwi/bdwlan.elf2:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/bdwlan.elf2 \
    vendor/samsung/dm3q/proprietary/vendor/firmware/kiwi/phy_ucode20.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/phy_ucode20.elf \
    vendor/samsung/dm3q/proprietary/vendor/firmware/kiwi/qdss_trace_config_v2.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/qdss_trace_config_v2.cfg \
    vendor/samsung/dm3q/proprietary/vendor/firmware/kiwi/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/kiwi/regdb.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/mfc/mfc_fw_flash.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc/mfc_fw_flash.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/mfc/mfc_fw_flash_cps4038.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc/mfc_fw_flash_cps4038.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/ois_mcu_stm32g_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ois_mcu_stm32g_fw.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/tsp_stm/fts2ba61y_dm3q.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tsp_stm/fts2ba61y_dm3q.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/vl53l8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/vl53l8.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/vpu20_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/vpu20_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v_unsigned.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/vpu30_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_4v.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/vpu30_4v_16mb.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_4v_16mb.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/vpu30_4v_16mb_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_4v_16mb_unsigned.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/vpu30_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_4v_unsigned.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v_unsigned.mbn \
    vendor/samsung/dm3q/proprietary/vendor/firmware/wez02_dm3_c0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wez02_dm3_c0.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/wez02_dm3_c1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wez02_dm3_c1.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/wez02_dm3_c2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wez02_dm3_c2.bin \
    vendor/samsung/dm3q/proprietary/vendor/firmware/wez02_dm3_c3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wez02_dm3_c3.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.sensormodule.0_lsi_s5khp2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.0_lsi_s5khp2.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.sensormodule.12_lsi_s5k3lu_full.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.12_lsi_s5k3lu_full.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.sensormodule.1_lsi_s5k3lu.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.1_lsi_s5k3lu.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.sensormodule.2_sony_imx564.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.2_sony_imx564.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.sensormodule.3_sony_imx754_x3.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.3_sony_imx754_x3.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.sensormodule.6_sony_imx754_x10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.sensormodule.6_sony_imx754_x10.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5k3lu.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5k3lu.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.tuned.lsi_s5khp2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.lsi_s5khp2.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx564.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx564.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx754_x10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx754_x10.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/com.samsung.tuned.sony_imx754_x3.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.samsung.tuned.sony_imx754_x3.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/t_t10_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/t_t10_dual_calibration.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/uw_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/uw_dual_calibration.bin \
    vendor/samsung/dm3q/proprietary/vendor/lib64/camera/w_dual_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/w_dual_calibration.bin

PRODUCT_PACKAGES += \
    btaudio_offload_if \
    com.samsung.ois.mcu_stm32g \
    com.samsung.sensor.hi1337 \
    com.samsung.sensor.hi847 \
    com.samsung.sensor.imx258 \
    com.samsung.sensor.imx374 \
    com.samsung.sensor.imx471 \
    com.samsung.sensor.imx564 \
    com.samsung.sensor.imx754 \
    com.samsung.sensor.s5k2ld \
    com.samsung.sensor.s5k3j1 \
    com.samsung.sensor.s5k3k1 \
    com.samsung.sensor.s5k3lu \
    com.samsung.sensor.s5kgn3 \
    com.samsung.sensor.s5khp2 \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.seg \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.samsung.node.capture_fusion \
    com.samsung.node.realtimebokeh \
    com.samsung.node.resolution \
    com.samsung.node.smooth_transition \
    com.samsung.node.uniplugin_capture \
    com.samsung.node.uniplugin_preview \
    com.samsung.node.uniplugin_recording \
    com.ss.stats.aec \
    com.ss.stats.af \
    com.ss.stats.awb \
    com.ss.stats.pdlib \
    libTsAeFront_dm3 \
    libTsAe_dm3 \
    libdepthmapwrapper_secure \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8550 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.settings.sm8550 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.mcx.policy.xr \
    com.qualcomm.qti.mcx.usecase.extension \
    android.hardware.bluetooth.audio-impl-qti \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.bluetooth@1.1-impl-qti \
    camera.qcom \
    com.qti.chi.offline \
    com.qti.chi.override \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.bttpi-impl \
    libPdSdCore \
    libSWB.camera.samsung \
    libTsAf_DM123Q \
    libTsAwbFront_DM3 \
    libTsAwb_DM3 \
    libbluetooth_audio_session_aidl_qti \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libbt-hidlclient \
    libbtnv \
    libcamerapostproc \
    libcamxexternalformatutils \
    libcamximageformatutils \
    libcamxswispiqmodule \
    libchifeature2 \
    libcom.qti.chinodeutils \
    libhypermotion_interface \
    libmulticam_image_optical_zoom \
    libmulticam_optical_zoom_control \
    libmulticam_video_optical_zoom \
    libsehbluetooth_audio_session_aidl \
    libsoc_helper \
    libswb_interface \
    libthirdparty_zoomtranslator_imp \
    sensors.flicker \
    sensors.grip \
    sensors.ssc \
    libaudiosaplus_sec \
    libsamsungSoundbooster_plus \
    libswdap \
    libswspatializer \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.bttpi-V2-ndk \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.samsung.hardware.bluetooth.a2dpsink@1.0 \
    vendor.samsung.hardware.bluetooth.audio-V1-ndk \
    vendor.samsung.hardware.bluetooth.audio-impl \
    vendor.samsung.hardware.bluetooth@2.0 \
    bttpi-saidl.xml \
    factory.ssc \
    android.hardware.bluetooth@1.1-service-qti \
    vendor.samsung.hardware.thermal@1.0-service \
    qms
